_base_: './our_default_test.yml'
data:
  dataset: ourdata_egoexo
  clip_length: 4
  
model:
  name: CLIP_OPENAI_TIMESFORMER_BASE
  pretrained_visual_checkpoint: null
  project_embed_dim: 256

train:
  epochs: 10
  batch_size: 16
  
test:
  testonly: true
  

resume: /path/to/checkpoint_best.pt
output: /path/to/target/



