_base_: './our_default.yml'
data:
  dataset: ourdata_egoexo
  clip_length: 4
  
model:
  name: CLIP_OPENAI_TIMESFORMER_BASE
  pretrained_visual_checkpoint: null
  project_embed_dim: 256

train:
  batch_size: 32

test:
  testonly: false

resume: /path/to/clip_openai_timesformer_base.narrator_rephraser.ep_0001.md5sum_02dbb9.pth
output: /path/to/target/
